---
- name: Instalar Docker en Debian 12.8.0
  hosts: all
  become: yes
  tasks:

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar dependencias necesarias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Añadir la clave GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Añadir el repositorio de Docker a APT
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        state: present

    - name: Actualizar lista de paquetes después de añadir Docker
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Habilitar y arrancar el servicio de Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Verificar la instalación de Docker
      command: docker --version
      register: docker_version

    - name: Mostrar versión de Docker
      debug:
        var: docker_version.stdout

