---
- name: Install Docker CE on Debian
  hosts: all
  become: yes
  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create the directory for APT keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      copy:
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: Update APT cache after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker CE and related tools
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Run Hello World container to verify Docker installation
      command: docker run hello-world
      register: docker_test
      ignore_errors: yes

    - name: Show Docker test output
      debug:
        var: docker_test.stdout





