---
- name: Install Docker CE on Debian
  hosts: all
  become: yes
  tasks:

    # Cleanup existing repository and key
    - name: Remove existing Docker repository file
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remove existing Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Clean APT cache
      shell: apt-get clean
      args:
        warn: false

    - name: Update APT cache
      apt:
        update_cache: yes

    # Install required dependencies
    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    # Add the Docker GPG key and repository
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      copy:
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename | default('bullseye') }} stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: Update APT cache after adding Docker repository
      apt:
        update_cache: yes

    # Install Docker CE
    - name: Install Docker CE and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    # Start Docker
    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    # Verify Docker installation
    - name: Run Hello World container to verify Docker installation
      command: docker run hello-world
      register: docker_test
      ignore_errors: yes

    - name: Show Docker test output
      debug:
        var: docker_test.s





