---
- name: Install Docker CE on Debian 12.8.0
  hosts: all
  become: yes
  tasks:

    - name: Ensure APT cache is up-to-date
      apt:
        update_cache: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Docker's GPG key
      command: >
        curl -fsSL https://download.docker.com/linux/debian/gpg |
        gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker APT repository
      copy:
        content: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable\n"
        dest: /etc/apt/sources.list.d/docker.list

    - name: Update APT cache after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker CE and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        var: docker_version.stdout


