---
- name: Instalar Docker en Debian 12.8.0
  hosts: all
  become: yes
  tasks:

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Instalar dependencias necesarias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: true

    - name: Añadir la clave GPG de Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      become: true

    - name: Añadir el repositorio de Docker a APT
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_major_version'] | int }} stable"
        state: present
      become: true

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
      become: true

    - name: Iniciar y habilitar el servicio de Docker
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Verificar que Docker está instalado y funcionando
      command: docker --version
      register: docker_version
      changed_when: false
      become: true

    - name: Mostrar la versión de Docker instalada
      debug:
        msg: "Docker versión: {{ docker_version.stdout }}"

